name: "Build and test"

on:
  push:
    branches: [ "tip-of-tree" ]
  pull_request:
    branches: [ "tip-of-tree" ]

permissions:
  contents: read

jobs:
  Build-and-test-Windows:
    strategy:
      matrix:
        platform: [Win32, x64]
        configuration: [Debug, Release]
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} .\Projects\VisualStudio

    - name: Test
      run: ${{ github.workspace }}\Projects\VisualStudio\maxGUIAutomatedTests\${{ matrix.platform }}\${{ matrix.configuration }}\maxGUIAutomatedTests.exe

  #Build-and-test-Linux:
  #  strategy:
  #    matrix:
  #      platform: [X86, X86-64]
  #      compiler: [Clang, GCC]
  #  runs-on: ubuntu-latest

  #  steps:
  #  - name: Checkout
  #    uses: actions/checkout@v3

  #  - name: Build
  #    working-directory: ${{env.GITHUB_WORKSPACE}}/Projects/${{ matrix.compiler }} ${{ matrix.platform }} Make
  #    run: make

  #  - name: Test
  #    run: ${{ github.workspace }}\Projects\