name: "Build and test"

on:
  push:
    branches: [ "tip-of-tree" ]
  pull_request:
    branches: [ "tip-of-tree" ]

permissions:
  contents: read

jobs:
  Windows:
    strategy:
      matrix:
        platform: [Win32, x64]
        configuration: [Debug, Release]
        runner: [windows-2025-vs2026, windows-11-vs2026-arm]
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Update NuGet packages
      run: nuget restore .\Projects\VisualStudio\maxGUI.sln

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} .\Projects\VisualStudio

    - name: Test
      run: ${{ github.workspace }}\Projects\VisualStudio\maxGUIAutomatedTests\${{ matrix.platform }}\${{ matrix.configuration }}\maxGUIAutomatedTests.exe

  Linux:
    strategy:
      matrix:
        platform: [X86-64]
        compiler: [Clang, GCC]
        runner: [ubuntu-26.04, ubuntu-26.04-arm, ubuntu-24.04, ubuntu-24.04-arm, ubuntu-22.04, ubuntu-22.04-arm]
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    #- name: Install Compilers
    #  run: |
    #       sudo apt update
    #       sudo apt install g++-9 g++-10 llvm-10 clang-10

    - name: Install Qt 5
      run: |
           sudo apt update
           sudo apt install -y qt6-base-dev qt6-declarative-dev libgl1-mesa-dev

    #- name: Find Qt
    #  run: |
    #       find /usr/include -name QWidget

    - name: Build
      #env:
      #  CXX: g++-10
      working-directory: ${{ github.workspace }}/Projects/Make
      run: make

    - name: Test
      run: ${{ github.workspace }}/Projects/Make/maxGUIAutomatedTests
